### ISSUE TITLE
4th Week 🚀 

### ISSUE THREAD

**Issue by dodoongtak** [CodeSoom/HowMuchMore#69]
### 1. 이 앱을 언제 사용하나요?
꿈만 같은 아파트에 살려면 현실적으로 얼마나 많은 돈을 더 저축해야 되는 지 알 수 있습니다.

#### 사용자는 
- 이름, 나이, 월 저축, 그리고 현재 은행잔고를 입력 할 수 있습니다.
- 살고싶은 아파트를 선택 할 수 있습니다. 
   - 4가지의 아파트 유형 중 하나를 선택.
      1. 한강뷰
      2. 주변 상권 우수
      3. 조경 우수
      4. 출퇴근 편리
         - 강남
         - 광화문
         - 여의도
         - 도심
   - 선택한 유형의 아파트들을 볼 수 있습니다.
      - 아파트 정보
        1. 이름 
        2. 전용면적 (m²)
        3. 지역
- 선택한 아파트를 구매할려면 얼마나 걸리는지 확인할 수 있습니다.
    - 아파트 가격 및 부가적인 정보
      1. 아파트 이름
      2. 평수 X -> m^2 로 고정 ( 2007년 정부에서 제곱미터로 시정 ※평은 일제강점기 잔여물)
      3. 가격
      4. 지역
      5. 지번
    - 아파트 구매까지에 대한 종합 정보 
      1. 필요한 금액
      2. 소요 기간
      3. 구매 시 나이

### 3. 이번 주가 지나면 사용자는 무엇을 할 수 있나요? 
- 꿈같은 아파트를 구매할려면, 얼마나 더 걸려야되는지 확인 할 수있습니다.
- 사용자 친화적인(?) 모바일 사이트를 사용 할 수 있습니다.
- 해당 사이트에 공유를 쉽게 할 수 있습니다. (링크 copy 기능)

### 4. 이번 주 에 구현 할 기능을 우선 순위대로 작성 해주세요.
(PR 단위)

#### 당장 실행 할 수 있는 tasks
- [x]  locale 원화로 표시
- [x]  숫자입력 시 한글로 출력 해주기
예시) 1000 입력하면 천만원

~~프로필 입력 후 다른 url 가기전에 route block 나가기전 유저에게 확인~~

- [x]  링크 공유 기능
  - [x] copy to clipboard
  - [x] share social media(facebook, twitter kakako)
  - [x] favicon 생성
  - [x] meta 생성
  
- [x] 아파트 유형s 추가

#### 추 후에 할 수 있는 tasks
**페이지 스타일링 - 디자인**
- [x]  Home
- [x]  Apartment - (아파트 이미지 일단 제외, 이미지 참고 할 수 있는 source 물색)
- [x]  Result
- [x]  Profile
- [x]  NewProfile
- [x]  Loading Image
- [x]  404

#### 이번주 일요일 자정 까지 꼭 해야 되는 tasks
- [x]  README like Pro
- [x]  영상 찍을 만한 디자인을 가진 사이트
- [x]  링크 공유 기능

#### 작업은
- 우선순위에 집중 Iteration을 더욱 빠르게, 피드를 더욱 많이.

#### 디자인은
- 통일성을 위한 디자인 시스템으로 관리
- layout/common UI component
- 문구는 부드럽게 구어체 (이과성향 버리기)

#### 코드는
- 캠프그라운드룰 따른 리팩터링
- COMMIT/PR/MERGE 이전에 각각 셀프리뷰

**Comment by dodoongtak** [comment]
#### 프로필(NewProfile) 입력 후 다른 url 가기전에 route block 페이지 이동 전 유저에게 확인 Prompt

TL;DR 해당 기능 보류.

history.block()으로 할 시에 alert로 구현을 하였지만....


```bash
useEffect(() => {
    const unblock = history.block('페이지에서 벗어나시겠습니까?');

    return () => {
      unblock();
    };
}, [history]);
```

해당 코드에서 history가 변동시 block에 넘겨준 문구가 alert로 나오게됩니다. 

구현은 했지만, 
![prompt_aler](https://user-images.githubusercontent.com/77006427/114383149-2ca97680-9bc8-11eb-9e88-1914c9743622.gif)

alert가 과연 좋은 UX일까?
`alert is evil` 이라는 문구가 기억나 찾아본 결과, 

어떤 이유가 됐든, UX관점으로는 alert는 사용을 하지 않는 것을 권장한다고합니다.

`About Face 3 by Alan Cooper`라는 책에서 상세하게 설명되있다고합니다. 

짧게 인용하자면...
> nearly every alert box which exists in current software is deeply wrong

>Do, don't ask.
Make all actions reversible.
Provide modeless feedback to help users avoid mistakes.

Modal로 따로 만들지 않는 한, alert는 자제해야되는게 맞지 않나싶습니다.

기환님 생각은 어떠신지 여쭤봐도 될까요?

**Comment by moonkii** [comment]
Modal 도 마찬가지로 사용성이 좋진 않아요.
저 같은 경우 필요하면 겉으로 보이는 모습만 Modal 처럼 보이게 하고 실제로는 CSS 의 position 속성 등을 이용해서 처리해주는 편이에요.

특별하게 alert 로 확인하는 이유가 있나요?
따로 에러 메시지나 유효성 검사가 필요한 경우 화면에 직접 보여주는게 더 효과적이에요.

**Comment by dodoongtak** [comment]
@moonkii 
> 특별하게 alert 로 확인하는 이유가 있나요?

수정 후 나가기 전 사용자에게 제대로 입력을 했는지 확인하는 의도로 modal이나 alert를 사용하고싶었습니다. 
(문구에서는 `이 페이지에서는 벗어나시겠습니까?` 지만)

굳이? 라고 생각하실 수 도 있겠지만, 보통 사이트를 사용하다보녀 이런 동작을 보실 거라 생각됩니다.

form을 입력하다 다른 페이지로 이동시에, 
1. `임시저장하시겠습니까?` 
2. `작성 도중에 페이지에서 벗어 나시겠습니까? 작성한 정보는 저장되지않습니다`
- `작성이 완료되지 않으셨습니다` <- 이 케이스는 alert나 modal 말고, 기환님이 말씀해준데로 바로 프론트에서 알려주는것으로 처리 가능하다는 것에 동의합니다

위 와 같은 이유들 중 제가 alert로 확인할려는 의도는 2번입니다!

**Comment by moonkii** [comment]
> 굳이? 라고 생각하실 수 도 있겠지만, 보통 사이트를 사용하다보면 이런 동작을 보셨을 거라 생각됩니다.

대부분이 UX 적으로 잘 못 사용하고 있는 사례라고 볼 수 있죠.

다들 쓴다고해서 좋은게 아니에요. 다들 쓰니까 그냥 따라하는 경우가 많죠.

'왜' 를 생각해보면 더 직관적이고 좋은 대안들이 많이 나올거에요.

**Comment by dodoongtak** [comment]
## 선택 갈림길 

4주 차 계획에 당장 실행할 수 있는 tasks가 끝났습니다. 

기환님이 앞서, 
스타일링은 나중에 '디자이너분에게 받아 꾸미기 시작해도 늦지 않는다' 피드가 기억납니다. 

다만 4주차 완성에 앞서서 이제부터, 
1. 피칭 영상을 찍을 사이트를 위해 스타일링을 완성하느냐,
2. 기능에 부족한 점들을 채우는냐,  

두개 중의 고민이 됩니다. 

### 현재 기능에서 개선 해야 될 부분
#### 1. 불러오는 아파트 데이터들이 실시간이 아닙니다. 
- [아파트랭킹이란 사이트](https://www.aptrank.com/)에서 아파트 이름/지번/거래날짜를 확인해, 
공공데이터포털 국토교통부 아파트매매 실거래자료에서 찾아서 가져옵니다. 
- 실거래자료에서 각 유형을 검색하는 로직을 짜기에는 시간이 현저히 부족하다고 생각됩니다. 
- 노드 스케줄러를 사용해 각 일마다 웹 스크랩핑을 해야 실시간 정보를 클라이언트사이드에 전달 할 수 있습니다.
- 클라이언트에서 매번 request마다 크롤링 하는건 리소스 및 장기간의 대기가 있기에, DB에 따로 저장해서 무리를 덜 하게

#### 2. 현재 아파트 구매까지의 예측 결과가 단순한 계산으로 이루어져있습니다.
- 이자율 + 인플레이션을 고려하지않은 단순 저축 및 현재잔고를 기반한 사칙연산입니다. 
- 해당 계산 방법에대해서는, 자료조사를 따로 실시해야됩니다. 

지금 현재 사이트를 지인들에게 피드를 기능에 대해 종합 해본 결과. 

1번 같은 경우는, 사용자는 모릅니다.  `아 그렇구나~` 라고 생각.
2번 같은 경우는, 근데 이거 어떻게 계산된거야? 가 결과 확인 후 꼭 나옵니다. 

디자인에 관해서는... 
넵. 다들 보기 불편하다 합니다. ㅎㅎ
HTML로만 이루어져있으니 당연지사.

1번을 선택하면, UX/UI에 관한 피드를 많이 받을 수 있을 것이고...
2번을 선택하면, 기능에 대해 개선을 할 수 있다... 하지만 피드는 받기 힘들다.

※피드를 받을 수 있는 마지막 주차라.
피드도 선택에 있어 중요한 기준 중에 하나라 생각됩니다.

### Q1
기환님이 현재 제 입장이라면, 
어떤 선택을 하실지 여쭤봐도 될까요?

**Comment by moonkii** [comment]
말씀드렸듯이 4주가 끝이 아니라 1차 배포라고 생각하시면 돼요.
당장 기능이 더 있는 것 보다 사용성을 고려해서 디자인을 추가하신게 더 반응이 좋으실거에요.
기능은 앞으로도 계속 조금씩 추가해 나간다 생각하시고 디자인을 마무리하시면 좋을 것 같아요.
이미 디자인에 관한 피드백도 받으셨으니 방향을 있으실거에요.
항상 사용자의 입장에서 생각하시는게 좋아요.

**Comment by dodoongtak** [comment]
@moonkii 

4주차 계획 👩‍🦽👨‍🦯🏃‍♂️
- [README](https://github.com/CodeSoom/HowMuchMore/blob/main/README.md) ✔
- [Changelog](https://github.com/CodeSoom/HowMuchMore/blob/main/CHANGELOG.md) ✔

일부 피드백 반영 😂😭😯😮
- ([UX](https://github.com/CodeSoom/HowMuchMore/issues/103) ✔
- [평 <-> m^2](https://github.com/CodeSoom/HowMuchMore/issues/103) ✔
- [legibility and readability reading number of price](https://github.com/CodeSoom/HowMuchMore/issues/100) ✔
- [Change Theme Color from 'Orange' to 'Blue'](https://github.com/CodeSoom/HowMuchMore/pull/114) ✔

 고생하셨습니다 ^^7;;
